Created Auth UI
theo-jedi/walletok-android pull request #2
Opened 2021-08-17 13:04 UTC by theo-jedi

Сделан интерфейс для страницы авторизации (Короткий онбординг)

2021-08-17 13:08 UTC, salonkasoli commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    android:paddingTop="54dp"
54 - многовато. Это отступ от верха экрана, а ты здесь указываешь оступ от статус бара. Предлагаю использовать 16 как везде

2021-08-17 13:09 UTC, salonkasoli commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    android:paddingEnd="20dp"
Почему 20, в макете 16 же

2021-08-17 13:09 UTC, salonkasoli commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        android:src="@drawable/ic_welcome_banner"
Насколько знаю, нужно использовать srcCompat. Студия не подсвечивает?

2021-08-17 13:10 UTC, theo-jedi commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    android:paddingTop="54dp"
Хорошо, в фигме просто не определен размер до статус бара был, сейчас поправлю

2021-08-17 13:10 UTC, salonkasoli commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        style="@style/TextAppearance.MaterialComponents.Headline6"
Если это textAppereance, то его нужно проставлять через тэг `android:textAppereance`. А вообще, зачем ты этот стиль проставил?

2021-08-17 13:11 UTC, salonkasoli commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        android:id="@+id/textView2"
Нужны нормальные айдишники для вьюх. textView2 и textView - ужас

2021-08-17 13:13 UTC, salonkasoli commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    <ImageView
Кнопку нужно сделать через Button, край через TextView. ImageView - это про картинки. Банальная проблема - у кнопки должна быть анимация нажатия

2021-08-17 13:15 UTC, salonkasoli commented on WalletOK/src/main/res/values/colors.xml
> +    <color name="dark_gray">#333333</color>
Этот цвет тут зачем? Вроде нигде не используется

2021-08-17 13:16 UTC, salonkasoli requested changes
Ждем правок

2021-08-17 13:17 UTC, theo-jedi commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        android:src="@drawable/ic_welcome_banner"
Не подсвечивает, точно заменить? Разница в android и app есть:
`android:src=""`
`app:srcCompat=""`

2021-08-17 13:18 UTC, theo-jedi commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        style="@style/TextAppearance.MaterialComponents.Headline6"
Чтобы задать заголовку черный цвет и толщину по тз. Прописать вручную, в теме стиль прописать или так оставить?

2021-08-17 13:19 UTC, theo-jedi commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        android:id="@+id/textView2"
Они автоматически появились, не заметил, конечно, уберу

2021-08-17 13:19 UTC, theo-jedi commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    <ImageView
Хорошо, была проблема с тем, что фон к кнопке  не применялся, буду разбираться

2021-08-17 13:20 UTC, theo-jedi commented on WalletOK/src/main/res/values/colors.xml
> +    <color name="dark_gray">#333333</color>
Создавал для кнопки как раз

2021-08-17 13:20 UTC, theo-jedi commented
Исправляю

2021-08-17 13:20 UTC, salonkasoli commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        android:src="@drawable/ic_welcome_banner"
Да, используем` app:srcCompat=""`

2021-08-17 13:22 UTC, theo-jedi commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        android:id="@+id/textView2"
Им вообще айдишники не нужны

2021-08-17 13:23 UTC, salonkasoli commented on WalletOK/src/main/res/layout/activity_auth.xml
> +        style="@style/TextAppearance.MaterialComponents.Headline6"
Ну, давай его пока использовать. Проставить через `textAppereance`

2021-08-17 13:53 UTC, salonkasoli commented on WalletOK/src/main/res/drawable/ic_auth_button.xml
> +  <solid android:color="@color/dark_gray" />
Кнопка без ripple эффекта? Или у нее есть анимация нажатия? Если нет - завести задачу в бэклог

2021-08-17 17:31 UTC, korefu commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    <androidx.appcompat.widget.AppCompatButton
Не лучше ли использовать MaterialButton? Там есть параметры и для радиуса, и для цвета, а еще можно вынести стиль кнопки отдельно, чтобы я его потом использовал

2021-08-17 17:47 UTC, theo-jedi commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    <androidx.appcompat.widget.AppCompatButton
У MaterialButton чего-то очень плохо со сменой фона, не получается нужного результата добиться. А зачем тебе потом стиль этой кнопки? Она ведь только на этой активности

2021-08-17 17:53 UTC, korefu commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    <androidx.appcompat.widget.AppCompatButton
app:backgroundTint не подходит? У меня такая же кнопка снизу

2021-08-17 18:02 UTC, theo-jedi commented on WalletOK/src/main/res/layout/activity_auth.xml
> +    <androidx.appcompat.widget.AppCompatButton
Не думал, что у него параметры для радиуса есть, заменил на MaterialButton

2021-08-17 20:47 UTC, korefu approved these changes

2021-08-18 06:58 UTC, salonkasoli approved these changes

2021-08-18 08:20 UTC, merged